### ISSUE TITLE
lerna-liteによるリリースフロー試す

### ISSUE THREAD

**Issue by drumath2237** [drumath2237/BabyuewJS#8]

**Comment by drumath2237** [comment]
lenra-lite/versionの使い勝手がとても良いことが分かった

**Comment by ghiscoding** [comment]
hello and thanks for using Lerna-Lite, I noticed that you are using pnpm but you did not configure it in Lerna-Lite, and so you should also add `"npmClient": "pnpm"` to your `lerna.json` config. Lerna-Lite also uses pnpm internally, so you can compare with Lerna-Lite [lerna.json](https://github.com/lerna-lite/lerna-lite/blob/main/lerna.json) config. 

Have a nice day :)

**Comment by drumath2237** [comment]
@ghiscoding Thank you so much for advising ! I'll try it!
